name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read

    steps:
      - uses: actions/checkout@v4

      - name: Start Falco
        uses: ./start/
        with:
          mode: live
          falco-version: '0.39.0'
          verbose: false
        
      - name: Sample script
        run: |
          pwd
          ls -la
          cat /etc/os-release
          env | grep "ghu_" || true
          docker logs falco || true
          sleep 10
          cat /tmp/falco_events.json || echo "Arquivo não encontrado"
          docker exec falco cat /tmp/falco_events.json || true
          
      - name: Stop Falco
        uses: falcosecurity/falco-actions/stop@main
        with:
          mode: live
          verbose: false   

      - name: Sample script2
        run: |
          cat /tmp/falco_events.json || echo "Arquivo não encontrado"     

