name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      actions: read

    steps:
      - uses: actions/checkout@v4

      - name: Start Falco
        uses: ./start/
        with:
          mode: live
          falco-version: '0.39.0'
          verbose: false
        
      - name: Threats
        run: |
          env | grep "ghu_" || true
          sleep 30

      - name: Check output
        run: |
          docker logs falco
          docker exec falco find / -type f -name "falco_events.json" 2>/dev/null

          
      - name: Stop Falco
        uses: falcosecurity/falco-actions/stop@main
        with:
          mode: live
          verbose: false   

