name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Start Falco
        # uses: falcosecurity/falco-actions/start@main
        uses: ./start/
        with:
          mode: live
          falco-version: '0.39.0'
          verbose: false
        
      - name: Threats
        run: |
          env | grep "ghu_" || true
          sleep 10
        
      - name: Copy results
        run: |
          docker exec falco ls -la /tmp || true
          docker cp falco:/tmp/falco_events.json /tmp/falco_events.json || true
          
      - name: Stop Falco
        uses: ./stop/
        with:
          mode: live
          verbose: false   

