name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read

    steps:
      - uses: actions/checkout@v4

      - name: Start Falco
        uses: falcosecurity/falco-actions/start@main
        with:
          mode: live
          falco-version: '0.39.0'
          verbose: true
        
      - name: Sample script
        run: |
          sleep 10
          cat /etc/os-release
          
      - name: Stop Falco
        uses: falcosecurity/falco-actions/stop@main
        with:
          mode: live
          verbose: true        

